# PRODUCTION config
title                    : "ONDATA"
url                      : "https://ondata.work" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
enforce_ssl              : "ondata.work"
comments:
  provider               : "staticman_v2"
staticman:
  branch                 : "master"

# exclude robots.txt for production
include:
  - _pages
  - _redirects
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - docs # ignore Minimal Mistakes /docs
  - test # ignore Minimal Mistakes /test
  - _posts/__notes.md
  - robots.txt
  - _posts/2017-05-13-rp17-was-wird-meinungen-sind-wie-daten.md

google_site_verification : 1TwKH7c-QhYqXsr6rCuld0ck3tE6BQvFVn-SCaBzNzY