# Production context: All deploys to the main
# repository branch will inherit these settings.
[context.production]
  command = "JEKYLL_ENV=production jekyll build --config _config.yml,_config_prod.yml"

# Deploy Preview context: All Deploy Previews
# will inherit these settings.
[context.deploy-preview]
  command = "JEKYLL_ENV=development jekyll build --config _config.yml,_config_prev.yml"

# Branch Deploy context: All deploys that are not in
# an active Deploy Preview will inherit these settings.
[context.branch-deploy]
  command = "JEKYLL_ENV=development jekyll build --config _config.yml,_config_prev.yml"

# building staticman as a netlify service
[build]
  command = "yarn build"
  functions = "functions"
  publish = "build"
  NODE_VERSION = "12"
  RUBY_VERSION = "2.6.2"
  YARN_VERSION = "1.19.1"
  RSA_PRIVATE_KEY = "-----BEGIN RSA PRIVATE KEY-----\nMIIEpAIBAAKCAQEAvZgV0xxo8mZUk3rfN5KspZsWaA5K7MyUQwMn4p6GhZdqEjQx beKrykuSyGiK0Thn1ZLiU6XO0iFCo+TpDcEdQHy2ax5aBnDR+5dhTCdCvo8EzzV/ Ti8K4v3uNu4Npqr76s27rhOZVteHSrV9zD50uvsSTZ+OV4+UkVN32GnzSepsCnxm SH1x7xyw1FsjSyZNxnnHjEInT7Zp6mpgmRRRpGB4Vjae2dZkjG3ae+3us0Vq1sIt TEFEzXqPCaCVWpqzg3nh2wTbNkYryfaUlSHZ7L0fRnVHcL/UVUT+nWxZACD0QNrw U21Cf8nPOwfv4qEhg1I9Yw6IpZgvZ7mAYr2UTQIDAQABAoIBAQC2Q22/vNEbLsrh 2L6cMzIsJlK9B/h5exaQ8Yi3cISMCwraozhdlgpmeI6MgQvqpFoV1JYlqgGQuo7Q 9nAhW+QeKYZIpi4PgQgs4NOVnSyp+t25wYk4BTtnCoymW+XdswRpLwzdBVRlSt9y L9XWsrgPROzMmLYDcTF3IBHXh8tt4vmAahaRWuw1hemAvtyaVA4JsDKi4MZ3ew9Q 866f2uY7e0hRbAUUr5IhKwqP1oKtBU6TUW1b1fli27MfsLI84CLivl1iRbl5SZp2 mvMyZtN4VDXaBOP+Oe9iwJEn0xkoDl43q8dWKX+ztfqrWybQbwqfG7ESgqkz0Y3D WEuBhmxVAoGBAOgF8SieyQVgtuxf9CEHGXC0ILBHnXZb8hsmWci3zQ1MIIWZJpg4 qH6iBMKLsR/in5HsGgFRDYfo/5hIxW/CoYmcxYCgDos9mHsjRSVeLJqovv808IKO 1Pg8ZQkxC7T4oNT+c+mUHRrAq6tP016G+4mVWFNmRGnVOmpGjkyZNt+HAoGBANEv s63Lw/KXKFJ0yGik1+3ylZFVWIspmW2zIQXeA3AfBCIY8+XPwRVu1S2oQYLWWk/v rNJPsnFbQRcj64Sm9ha2+/VWyo9QabQ1sfWbWpgtlbrywJv15Z6jEVxTJb9Tbuq/ zMeJ9FyhKQtula8bajEfm691eYJ/M/Co+/mlbZqLAoGAUE1OK7rY4+2XIbQL8Cpe 2azd62S90Kr93ful81v5sfJ5BwP8YY6qcjls4FAsm1Z5160ZSv9caX9whqoY+xcn hVMm39+FaReGYIfSdJ5lXZmtkPInk2gPuWJdrZK19IpgT5dJUrwaXpn0UDQueXbK M9HmYebxIpfTwdhtg4E7hp0CgYA+H6OF3rjfp6Jy8nm+Eg6KfPuMQMNd+Mm2+Xa6 LlfpCV0J3003l75o5hRrTce+2nfRu4UgpEiDP62R+LnuGEOHNWqYTuEzNJdfzH6A SVXbUdZgwc0PxDQgK59xQsQ4EMgk8TcYn1Cx3a651WqgqUydMBzlO8cNSUecliLW 3hkxxwKBgQCzrnYr1G2qOmAW7ptjcq3HGtQ9NdmdEalYNNAGwO9fP5a2uy2tEwH1 pneraHnpXkOGj92SHDx4rq8HtrkOcl4XsP3KOJMqKgBvK42nGhtnp5kfniGIguU8 ccOcQ7fpbiz6OnWcVTO3c7h1obphyLlMzi07uSrmpKbaGNmOdB30HQ==\n-----END RSA PRIVATE KEY-----"
  GITHUB_TOKEN = "b167b8091407f0ca2eb29e8fee8371fcf440221e"