_id: 117256c0-1891-11e7-9031-e36613b494d7
_parent: 'http://ondata.local/deployment-jekyll-with-github-and-netlify/'
message: "Antwort an HoKr: Na Klar doch.\r\nviele Grüße"
name: developer
email: 87ce45c556070c9c386a19a50439132c
url: ''
replying_to: '3'
hidden: ''
date: '2017-04-03T17:15:00.584Z'
timestamp: 1491239700
layout: post
