_id: 896d4dc0-1f0c-11e7-adb7-59c4d8587a3a
_parent: /deployment-jekyll-with-github-and-netlify/
message: 'Neuer KOmmentar sollte unter erscheinen unter hk 2017-04-12 01:13:34 +02:00'
name: fd
email: 983dde02f251ae32f24ab32de7b9ba16
url: ''
replying_to: ''
hidden: ''
date: '2017-04-11T23:13:56.986Z'
