_id: a2ff7170-249b-11e7-90de-bd93bc33a643
_parent: 'https://ondata.work/deployment-jekyll-with-github-and-netlify/'
message: noch ein Test
name: Holger Kral
email: 7ac457315070721ddf4351bf594b0086
url: ''
replying_to: ''
hidden: ''
date: '2017-04-19T01:00:53.888Z'
