_id: b846ac00-18c6-11e7-9031-e36613b494d7
_parent: 'http://ondata.local/deployment-jekyll-with-github-and-netlify/'
message: Testantwort an HK Teatkommentar 01
name: developer
email: 87ce45c556070c9c386a19a50439132c
url: ''
replying_to: '1'
hidden: ''
date: '2017-04-03T23:39:03.789Z'
timestamp: 1491262743
layout: post
