_id: 3c601e10-2482-11e7-90de-bd93bc33a643
_parent: 'https://ondata.work/deployment-jekyll-with-github-and-netlify/'
message: Erster Testkommentar
name: Holger Kral
email: 87ce45c556070c9c386a19a50439132c
url: ''
replying_to: ''
hidden: ''
date: '2017-04-18T21:59:04.207Z'
