_id: 05a89520-2499-11e7-90de-bd93bc33a643
_parent: 'https://ondata.work/deployment-jekyll-with-github-and-netlify/'
message: Testantwort
name: Ich
email: 689da697719f9da90abce5b908c7f343
url: ''
replying_to: '1'
hidden: ''
date: '2017-04-19T00:42:10.794Z'
