_id: 59099af0-1578-11e7-bddc-ed6a4b7bfabf
_parent: /deployment-jekyll-with-github-pages-and-netlify/
message: 'Und Antwort an TesterTwo: sehr schön.'
name: TesterFour
email: 87ce45c556070c9c386a19a50439132c
url: ''
replying_to: '2'
hidden: ''
date: '2017-03-30T18:40:29.666Z'
timestamp: 1490899229
