_id: 7ee96660-18fc-11e7-924d-b313c1e1b5eb
_parent: /deployment-jekyll-with-github-and-netlify/
message: Test1
name: HK
email: 983dde02f251ae32f24ab32de7b9ba16
url: ''
replying_to: ''
hidden: ''
date: '2017-04-04T06:04:00.394Z'
