_id: 0b243cb0-1a8b-11e7-9d22-9b434ef38faa
_parent: /deployment-jekyll-with-github-and-netlify/
message: Antwort an ON
name: 'Off'
email: 43ef4a5a0da01f11c52fa6d7fac049c7
url: ''
replying_to: '3'
hidden: ''
date: '2017-04-06T05:36:55.461Z'
