_id: 74ed43f0-193f-11e7-924d-b313c1e1b5eb
_parent: 'http://ondata.local/deployment-jekyll-with-github-and-netlify/'
message: Testantwort HK Test1
name: EO
email: 31d79c7644157801425b31adbbbcfc29
url: ''
replying_to: '2'
hidden: ''
date: '2017-04-04T14:03:23.539Z'
