_id: 2cc0d1c0-1a41-11e7-82b2-1f8592dc6023
_parent: 'https://0ndata.de/deployment-jekyll-with-github-and-netlify/'
message: testkommentar ondata
name: 'on'
email: 983dde02f251ae32f24ab32de7b9ba16
url: ''
replying_to: ''
hidden: ''
date: '2017-04-05T20:48:09.062Z'
