_id: 63f53520-2499-11e7-90de-bd93bc33a643
_parent: 'https://ondata.work/deployment-jekyll-with-github-and-netlify/'
message: Und  noch ein Kommentar
name: Er
email: 983dde02f251ae32f24ab32de7b9ba16
url: ''
replying_to: ''
hidden: ''
date: '2017-04-19T00:44:49.005Z'
