_id: d2e2c9e0-18a8-11e7-9031-e36613b494d7
_parent: 'http://ondata.local/deployment-jekyll-with-github-and-netlify/'
message: Testantwort an HK
name: developer
email: 87ce45c556070c9c386a19a50439132c
url: ''
replying_to: '4'
hidden: ''
date: '2017-04-03T20:05:03.565Z'
timestamp: 1491249903
layout: post
