_id: 86fa0500-1562-11e7-bddc-ed6a4b7bfabf
_parent: /deployment-jekyll-with-github-pages-and-netlify/
message: Antwort an Holger
name: Von mir
email: 983dde02f251ae32f24ab32de7b9ba16
url: ''
replying_to: '2'
hidden: ''
date: '2017-03-30T16:04:17.840Z'
timestamp: 1490889857
